### ISSUE TITLE
[Feature] range preview | QoL

### ISSUE THREAD

**Issue by rlnt** [SuperMartijn642/ItemCollectors#10]
**Is your feature request related to a problem? Please describe.**
We consider to add this mod to the All The Mods modpacks because it has significantly better performance than competitor mods. Awesome work so far!
When testing it, we quickly realized that many players are kind of confused by the range information.
Like does the range count from the Collector in each direction or is it an area around the Collector with those dimensions.

**Describe the solution you'd like**
It would be very handy to have a button in the screen of the Tile Entity which lets you enable a client-side preview of the range the Collector covers. Since you can also adjust the distance settings in the config, it would be nice if this preview respects those options and is able to show you the range depending on the mod settings.
This could maybe look like the range previews from Industrial Foregoing and either it's enabled until you disable it again with the same button or it will deactivate itself after like 30 seconds or so.

**Comment by SuperMartijn642** [comment]
This should already be present after version 1.1.0. 🙂

**Comment by rlnt** [comment]
That's indeed the case but right now it's only the outline of the edges which makes it hard to see when the range is large.
A slightly transparent coloring of the walls would be very nice.

Edit: Do you plan to add configurable output sides in the future as well? That would be very handy.

**Comment by SuperMartijn642** [comment]
Yeah that's indeed a good idea to make the walls visible, I will have to see when I have time to add it.

As for the configurable outputs, I think being able to rotate the collectors should already be enough. I don't see many scenarios where multiple outputs would help all that much.

**Comment by rlnt** [comment]
I wasn't aware you can rotate them, haha. Thank you!

**Comment by SuperMartijn642** [comment]
The walls of the operating area are now also visible as of version 1.1.3.

Thank you for the suggestion!
