### ISSUE TITLE
Item collectors encountered an error

### ISSUE THREAD

**Issue by Baggytrousers27** [SuperMartijn642/ItemCollectors#11]
supermartijn642configlib-1.0.9-mc1.17
supermartijn642corelib-1.0.12-mc1.17
Itemcollectors 1.1.2 mc1.17
Forge 17.17.1-37.0.31(33)

Item collectors (itemcollectors) encountered an error during the common_setup event phase.

Item collectors (itemcollectors) encountered an error during the error event phase.

[Crashllog](https://pastebin.com/Kv3rdjdg).

**Comment by SuperMartijn642** [comment]
Forge 37.0.31 had a breaking change. Until I update it, you could downgrade to Forge 37.0.30 or lower.

**Comment by SuperMartijn642** [comment]
I fixed it now in Item Collectors version 1.1.2a.

Thank you for reporting the issue!
