### ISSUE TITLE
[Bug] Item Collector cannot be found in creative menu. Only by Item Search

### ISSUE THREAD

**Issue by RedBeast1959** [SuperMartijn642/ItemCollectors#17]
**Version Info**
- Minecraft: 1.19.2
- Forge: 43.1.3
- Item Collectors: itemcollectors-1.1.5b-forge-mc1.19.jar

**Description of the Bug**
...
There's no proper creative menu for Item Collectors Mod. In creative mod, I can only find them by item search bar.

**Steps to Reproduce**
...

**Screenshots**
...
![2022-09-04_23 54 45](https://user-images.githubusercontent.com/100399264/188320291-6ba5b515-1df1-4e8d-8658-33dfd003e158.png)

**Comment by SuperMartijn642** [comment]
I've now added the items to the decorations creative tab in version 1.1.6.

Thank you for reporting the issue!
