### ISSUE TITLE
[Crash] client method crash

### ISSUE THREAD

**Issue by bigenergy** [SuperMartijn642/ItemCollectors#22]
**Version Info**
- Minecraft, 1.18.2
- Item Collectors, 1.1.6
**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
https://gist.github.com/bigenergy/882b93a84251da0a93ae6a56ebfba65b

**Comment by bigenergy** [comment]
@SuperMartijn642 will you fix it? the error seems to be in your mod-core

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.3 of my core library.

Thank you for reporting the issue!
