### ISSUE TITLE
[Question] ...1.19.4 for Forge?

### ISSUE THREAD

**Issue by Aetrnl94** [SuperMartijn642/ItemCollectors#23]
**Question**
...
Hi, this mod looks amazing! Does it work on 1.19.4 for Forge, and if not, any plans on updating it (and if-so, when)? Thanks!

**Comment by SuperMartijn642** [comment]
Item Collectors is already available for forge on 1.19.4.

**Comment by Aetrnl94** [comment]
Whoops, thank you so much! I didn't see it at first haha
