### ISSUE TITLE
[Bug] Duplication glitch with FTB Quests

### ISSUE THREAD

**Issue by Asek3** [SuperMartijn642/ItemCollectors#24]
**Version Info**
- Minecraft, 1.16.5
- Item Collectors, 1605.2.5-build.9

**Steps to Reproduce**

https://user-images.githubusercontent.com/64613894/234777456-20715bf4-9dd8-42f4-8899-d17326bee8d8.mp4

**Comment by SuperMartijn642** [comment]
> 1605.2.5-build.9

That is not a version of Item Collectors 🤔The version should be in the file name, something like `itemcollectors-forge/fabric-mc1.x.jar`.

**Comment by Asek3** [comment]
bruh i copied ftb quests version. I mean 1.1.7-forge

**Comment by SuperMartijn642** [comment]
I can't find version 1605.2.5-build.9 of FTB Quests on CurseForge.
I tested it with FTB Quests version 1605.3.4-build.90, but I cannot reproduce the issue.
