### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by SikiciBebek** [SuperMartijn642/ItemCollectors#25]
**Version Info**
- Minecraft, 1.19.2
- Item Collectors, itemcollectors-1.1.7-forge-mc1.19.jar

**Steps to Reproduce**
Place and look in the direction

**Crash report (~/logs/latest.log)**
Crash-report: https://pastebin.com/TD8Ymu07
Logs: https://gist.github.com/SikiciBebek/ac104718d788cb06dbc4e51ec5154a01

**Comment by SuperMartijn642** [comment]
> java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "com.corosus.out_of_sight.OutOfSight.getCanonicalNameCached(java.lang.Class)" is null

Seems to be caused by Out Of Sight. Please report the issue to them.

**Comment by SikiciBebek** [comment]
Ty^^
