### ISSUE TITLE
[Bug] Item Collectors don't work on expanded storage mod chests 

### ISSUE THREAD

**Issue by Arshia-D** [SuperMartijn642/ItemCollectors#26]
**Version Info**
- Minecraft, 1.19.2 Forge
- Item Collectors, itemcollectors-1.1.7-forge-mc1.19

**Description of the Bug**
I can insert items to this chests with a hopper but Item Collectors don't work on expanded storage chests 
Expanded Storage (https://www.curseforge.com/minecraft/mc-mods/expanded-storage)

**Steps to Reproduce**
Place mod chest then place Item Collector on it it dont work 

**Screenshots**
![image_2023-06-24_185320695](https://github.com/SuperMartijn642/ItemCollectors/assets/107769294/902208f1-5a36-4285-8edf-ab58c53d639e)
![image](https://github.com/SuperMartijn642/ItemCollectors/assets/107769294/4b4f2122-046c-46cf-ad93-e5e72f989c44)

**Comment by SuperMartijn642** [comment]
It appears to be working fine: https://imgur.com/kO0qa2e.gif

**Comment by Arshia-D** [comment]
> It appears to be working fine: https://imgur.com/kO0qa2e.gif

So this is a mod conflict  ?

**Comment by SuperMartijn642** [comment]
No clue honestly 🤷‍♂️

**Comment by Arshia-D** [comment]
> No clue honestly 🤷‍♂️

Find the problem; it's because of Optifine. I don't know why, but without it, it works fine.

**Comment by SuperMartijn642** [comment]
That is... interesting. It is impressive how OptiFine seemingly manages to break any random thing.
Not much I can do about it sadly, OptiFine is closed source so I can't know what it changes. I guess just don't use OptiFine. If you want OptiFine for shaders, you can use Oculus as an alternative.

For now I'll close the issue, thank you for reporting it though!
