### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by iamtyroon** [SuperMartijn642/ItemCollectors#27]
**Minecraft Fabric **
- Minecraft,1.19.2 ...
- Item Collectors, ...

**item filter loses texture with some mods im trying my best to find the solution and maybe remove the mod that causes this texture error but it'd be better if it didn't have this problem in the first place   **

![2023-09-08_19 21 07](https://github.com/SuperMartijn642/ItemCollectors/assets/105237183/5d0a9c2a-aa94-4776-9870-d46c66ed949d)

**Comment by SuperMartijn642** [comment]
If you are using ThonkUtil, that's probably it. ThonkUtil breaks any models not located in a subfolder, a bunch of mods are affected by it.
I believe they did fix it for 1.19.2, so try updating the mod.

As a side not, please fill in the mod version when creating a bug report.

**Comment by iamtyroon** [comment]
i dont think thats it coz i just removed thonk util but still getting the texture error

**Comment by SuperMartijn642** [comment]
It works fine with just Item Collectors 1.1.8 installed on Fabric 1.19.2. Please narrow down the mods needed to reproduce the issue.

> As a side not, please fill in the mod version when creating a bug report.

What version of Item Collectors are you using?

**Comment by iamtyroon** [comment]
item collector 1.1.8 for fabric 1.19.2

**Comment by iamtyroon** [comment]
im trying my best to snuff out the mod that causes this error

**Comment by iamtyroon** [comment]
i removed end goblin traders and it worked out

**Comment by SuperMartijn642** [comment]
Even with Goblin Traders installed, the item collectors look normal. I don't see how Goblin Traders would even mess with block models 🤔

**Comment by iamtyroon** [comment]
not the main goblin traders im talking about the end goblin traders variant
idk tho it worked so im good
