### ISSUE TITLE
[Bug] Crashed

### ISSUE THREAD

**Issue by goodguyham** [SuperMartijn642/ItemCollectors#28]
**Version Info** 
1.20.1
- Minecraft, fabric
- Item Collectors, the basic one, have not tried advanced

**Description of the Bug**
crashed when i placed the item collector and was not able to load back my world until i unchecked **enhanced block entities**, which is weird because i have used the collector block before with that mod on and have not crashed
idk if your mod caused the crash due to incompatibility or EBN, i'm just reporting the crash ay

**Steps to Reproduce**
i have no idea but in the chunk i placed the item collector in had cows floating on water and a dispenser. 'm not sure if it matters
**Screenshots**
...

**Comment by SuperMartijn642** [comment]
What version of Item Collectors are you using? Please share the crash log.

**Comment by goodguyham** [comment]
its 1.1.8

here's the crash log: https://gnomebot.dev/paste/1157203269429514261

**Comment by SuperMartijn642** [comment]
As far as I can tell it is not caused directly by Item Collectors as nothing from Item Collectors is in the logs.
My guess is that something is not handling rendering correctly and it just coincidentally works fine with how vanilla initializes rendering block entities. But as soon as something else renders before it, it breaks.

> until i unchecked enhanced block entities

I am not familiar with that. What do you mean by enhanced block entities?

**Comment by goodguyham** [comment]
its this mod.
 https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities


> My guess is that something is not handling rendering correctly and it just coincidentally works fine with how vanilla initializes rendering block entities.

aight so it might be a problem on that mod's behalf not urs ok
