### ISSUE TITLE
[Question] Language file is not running

### ISSUE THREAD

**Issue by meishiffx** [SuperMartijn642/ItemCollectors#29]
I see that the language file exists, but I can only see English.

**Comment by SuperMartijn642** [comment]
What language file?

**Comment by meishiffx** [comment]
I use 1.1.8-forge-mc1.18 mod.Tested in Chinese and Russian

**Comment by SuperMartijn642** [comment]
Both Chinese and Russian translations seem to be working fine 🤔
![image](https://github.com/SuperMartijn642/ItemCollectors/assets/12382965/b9992b92-7de8-4192-a5c7-c1039cbfe197)
![image](https://github.com/SuperMartijn642/ItemCollectors/assets/12382965/5458e072-398c-4011-a400-0f9311e7a87a)

**Comment by meishiffx** [comment]
It does not work when displaying the item name, but the gui displays it😂.
Might be a compatibility issue with other mods
