### ISSUE TITLE
[1.15.2] tier bug when broken.

### ISSUE THREAD

**Issue by Bass2style** [SuperMartijn642/ItemCollectors#3]
when breaking an advanced item collector, he became a simple collector.

conditions : 
- environment : online multiplayer server.
- forge : 31.2.36
- mod version : 1.0.3

logs or something : 
- yt vidéo : https://youtu.be/tHmZ40Eox7c

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.4.

Thanks for the report!

**Comment by Bass2style** [comment]
Thanks for the fix. :D
