### ISSUE TITLE
[Crash] Description: Ticking block entity

### ISSUE THREAD

**Issue by PeakXing** [SuperMartijn642/ItemCollectors#31]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2024-01-02 19:45:45
Description: Ticking block entity

java.lang.IllegalArgumentException: Transfer variant may not be blank.
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:63)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:35)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:67)
	at com.supermartijn642.itemcollectors.CollectorBlockEntity.update(CollectorBlockEntity.java:88)
	at com.supermartijn642.core.block.EntityHoldingBlock.lambda$getTicker$0(EntityHoldingBlock.java:30)
	at net.minecraft.class_2818$class_5563.redirect$zpk000$carpet$checkProcessBEs(class_2818.java:790)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zph000$carpet$modifiedRunLoop(MinecraftServer.java:9942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:63)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:35)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:67)
	at com.supermartijn642.itemcollectors.CollectorBlockEntity.update(CollectorBlockEntity.java:88)
	at com.supermartijn642.core.block.EntityHoldingBlock.lambda$getTicker$0(EntityHoldingBlock.java:30)
	at net.minecraft.class_2818$class_5563.redirect$zpk000$carpet$checkProcessBEs(class_2818.java:790)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: itemcollectors:basic_collector_tile // com.supermartijn642.itemcollectors.CollectorBlockEntity
	Block: Block{itemcollectors:basic_collector}[facing=south]
	Block location: World: (-835,93,-1974), Section: (at 13,13,10 in -53,5,-124; chunk contains blocks -848,-64,-1984 to -833,319,-1969), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,-64,-2048 to -513,319,-1537)
	Block: Block{itemcollectors:basic_collector}[facing=south]
	Block location: World: (-835,93,-1974), Section: (at 13,13,10 in -53,5,-124; chunk contains blocks -848,-64,-1984 to -833,319,-1969), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,-64,-2048 to -513,319,-1537)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zph000$carpet$modifiedRunLoop(MinecraftServer.java:9942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 3170
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,77,80), Section: (at 0,13,0 in 10,4,5; chunk contains blocks 160,-64,80 to 175,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2102746 game time, 2934863 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 6999 (now: true), thunder time: 50247 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zph000$carpet$modifiedRunLoop(MinecraftServer.java:9942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.2.0-31-generic
	Java Version: 18, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2464745088 bytes (2350 MiB) / 4424990720 bytes (4220 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12600K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 4.90
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: AlderLake-S GT1
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x4680
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 34066.93
	Virtual memory used (MB): 37625.26
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 147.33
	JVM Flags: 2 total; -Xms1G -Xmx8G
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.5
		amethystgravity: Amethyst Gravity: Reattracted 2.0.0+1.20.1
			cicada: CICADA 0.5.2+1.20.1-minus
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.0.6+1.20.1
		architectury: Architectury 9.1.12
		artifacts: Artifacts 9.2.0
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		athena: Athena 3.1.1
		azurelibarmor: AzureLib Armor 2.0.3
		bakery: Bakery 1.1.3
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		botarium: Botarium 2.2.1
		brewinandchewin: Brewin And Chewin fabric-2.3.1+1.20.1
		candlelight: Candlelight 1.2.8
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carpet: Carpet Mod 1.4.112+v230608
		carpeted: Carpeted 1.20-1.4
		carryon: Carry On 2.1.2.7
		chipped: Chipped 3.0.1
		chunkloaders: Chunk Loaders 1.2.8+a
		chunksending: Chunksending Mod 1.20.1-2.8
		clickadv: Clickable Advancements Mod 1.20.1-3.7
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		coloredendcrystals: ColoredEndCrystals 1.0.1
		completeconfig: CompleteConfig 2.5.2
			completeconfig-base: completeconfig-base 2.5.2
		create: Create 0.5.1-d-local+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.99999+1.20
			porting_lib_base: Porting Lib Base 2.1.99999+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.99999+1.20
				porting_lib_utility: Porting Lib Utility 2.1.99999+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.99999+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.99999+1.20
			porting_lib_entity: Porting Lib Entity 2.1.99999+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.99999+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.99999+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.99999+1.20
				porting_lib_common: Porting Lib Common 2.1.99999+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.99999+1.20
			porting_lib_models: Porting Lib Models 2.1.99999+1.20
			porting_lib_networking: Porting Lib Networking 2.1.99999+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.99999+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.99999+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.99999+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.99999+1.20
				porting_lib_core: Porting Lib Core 2.1.99999+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.99999+1.20
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.11
			create_dragon_lib: Create Dragon Lib 1.4.1
		create_jetpack: Create Jetpack 4.1.0
			flightlib: Flight Lib 2.0.3
		create_new_age: Create: New Age 1.1.1
		create_so: Create: Sandpaper Overhaul 1.6+1.20.1
		create_structures: Create: Structures 1.1.0
		createdieselgenerators: Create Diesel Generators 2.1.3
		createoreexcavation: Create Ore Excavation 1.4.2
			chunk-storage-api-fabric: Chunk Storage Api Fabric 1.0.3
		creeperoverhaul: Creeper Overhaul 3.0.1
		crittersandcompanions: Critters and Companions 1.20.1-2.0.3
		croptopia: Croptopia 3.0.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.6
		culturaldelights: Cultural Delights Fabric 0.14.11+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		cupboard: cupboard 1.20.1-2.2
		customportals: Custom Portals 3.3.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
		deeperdarker: Deeper and Darker 1.2.5
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		delightfulcreators: Delightful Creators 1.1.8
		doapi: Lets Do Api 1.2.8
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
		dungeons_arise: When Dungeons Arise 2.1.57
		dungeons_arise_seven_seas: When Dungeons Arise: Seven Seas 1.0.2
		easyanvils: Easy Anvils 8.0.1
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.1
			puzzlesapi: Puzzles Api 8.1.4
		ecologics: Ecologics 2.2.0
		elytraslot: Elytra Slot 6.3.0+1.20.1
		enchantinginfuser: Enchanting Infuser 8.0.2
		endermanoverhaul: Enderman Overhaul 1.0.3
		endrem: End Remastered 5.2.4
		ends_delight: End's Delight 1.0.1
		enhancedworkbenches: Enhanced Workbenches 1.1+1.20.1
		epherolib: EpheroLib 1.2.0
		expandeddelight: Expanded Delight 0.3.0.2
		expandedstorage: Expanded Storage 10.1.1
		exposure: Exposure 1.2.1
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		fabricproxy-lite: FabricProxy Lite 2.6.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmersrespite: Farmer's Respite 2.3.4
		ferritecore: FerriteCore 6.0.1
		fishingreal: Fishingreal 1.20.1-1.7.1
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.3
		formationsoverworld: Formations Overworld 1.0.2
		friendsandfoes: Friends&Foes 2.0.6
		frightsdelight: Frights Delight 1.20.1-1.0.1
		fusion: Fusion 1.1.0+c
		garnished: Create: Garnished 1.4+1.20.1
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		gravity_changer_q: Gravity Changer (qouteall fork) 1.1.2
		handcrafted: Handcrafted 3.0.5
		herbalbrews: Herbal Brews 1.0.2
		icarus: Icarus 1.16
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		interactic: Interactic 0.2.0+1.20
		itemcollectors: Item Collectors 1.1.8
		jade: Jade 11.7.0
		jadeaddons: Jade Addons 5.2.3
		java: OpenJDK 64-Bit Server VM 18
		jmc: Just More Cakes! 1.13.1
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn 1.2.0
		lithium: Lithium 0.11.2
		lookinsharp: Lookin' Sharp! 1.0.2
			reach-entity-attributes: Reach Entity Attributes 2.4.1
		magiclib: MagicLib 0.7.398+fe2125a-stable
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.398+fe2125a-stable
		meadow: Meadow 1.3.3
		minecraft: Minecraft 1.20.1
		mobscarecrow: Mob Scarecrow 2.3.0
		modernfix: ModernFix 5.11.1+mc1.20.1
		moonfabric: moonfabric mod 1.3.1
		moonlight: Moonlight 1.20-2.8.78
		more_armor_trims: More Armor Trims 1.1.3-1.20.1
		mr_ctov_createstructures: CTOV - Create: Structures 1.0
		mr_dungeons_andtavernsancientcityoverhaul: Dungeons and Taverns Ancient City Overhaul 1
		mr_dungeons_andtavernsstrongholdrework: Dungeons and Taverns Stronghold Rework 1
		mr_edf_remastered: Ender Dragon Fight Remastered 4.3
		mythic_charms: Mythic Charms 0.6.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		naturalist: Naturalist 4.0.3
		natures_spirit: Nature's Spirit 1.3.0.3
		nethersdelight: Nether's Delight 1.0.0
		nethervinery: Nether Vinery 2.0.2
		nightlights: Night Lights 1.1
		noisium: Noisium 1.0.2+mc1.20.x
		overweight_farming: Overweight Farming 1.20.1-2.0.3-fabric
			midnightlib: MidnightLib 1.4.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		paladins: Paladins & Priests (RPG Series) 1.0.4+1.20.1
		paxi: Paxi 1.20-Fabric-4.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puzzleslib: Puzzles Lib 8.1.11
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		reborncore: Reborn Core 5.8.7
		rechiseled: Rechiseled 1.1.5+b
		rechiseledcreate: Rechiseled: Create 1.0.1
		repurposed_structures: Repurposed Structures 7.1.11+1.20.1-fabric
		resourcefulconfig: Resourcefulconfig 2.1.0
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respitecreators: Respite Creators 1.2.0
		runes: Runes 0.9.10+1.20.1
		skyvillages: Sky Villages 1.0.3.2-1.19.2-1.20.1
		sliceanddice: Create Slice & Dice 3.0.0
		smoothchunk: Smooth chunk save Mod 1.20.1-3.5
		snowyspirit: Snowy Spirit 1.20-2.2.6
		spell_engine: Spell Engine 0.12.4+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		sprout: Sprout 1.5.0
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.17
			mixinsquared: MixinSquared 0.1.1
		suppsquared: Supplementaries Squared 1.20-1.1.12
		techreborn: Tech Reborn 5.8.7
			team_reborn_energy: Energy 3.0.0
		tempad: Tempad 2.3.1
		terrablender: TerraBlender 3.0.0.169
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		trinkets: Trinkets 3.7.1
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		vinery: Vinery 1.4.7
		wizards: Wizards (RPG Series) 1.0.4+1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['PeakXing'/208, l='ServerLevel[world]', x=-50.13, y=153.98, z=-155.19]]
	Data Packs: vanilla, fabric, Snowyspirit Generated Pack, Supplementaries Generated Pack, Suppsquared Generated Pack, natures_spirit:modified_badlands, natures_spirit:modified_dark_forest, natures_spirit:modified_mountain_biomes, natures_spirit:modified_savannas, natures_spirit:modified_swamp, ctov-creates-structures-add-on-v1-0.zip, Repurposed_Structures-Better_Dungeons_v5.zip, ctov-friends-and-foes-add-on-v2-0.zip, ctov-chefs-delight-add-on-v2-0.zip, Repurposed_Structures-Farmers_Delight_v6.zip, Repurposed_Structures-Chef's_Delight_v3.zip, Repurposed_Structures-Better_Witch_Huts_v4.zip, No_Old_Caves_V1.1.zip, Repurposed_Structures-Better_Monuments_v6.zip, Repurposed_Structures-Better_Desert_Temples_v8.zip, Repurposed_Structures-Friends_And_Foes_v6.zip (incompatible), Repurposed_Structures-Better_Strongholds_v5.zip, Repurposed_Structures-Better_Jungle_Temples_v5.zip, LessStructures-SpacingTweaks-1.20.1-2.1.56.zip, ctov-croptopia-add-on-v2-0.zip, Repurposed_Structures-Better_Nether_Fortress_v6.zip, ctov-farmers-delight-add-on-v2-1a.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	-----------------------------------------------
	Here is the translation of the text you provided:

“Here is my error report. I have a two-dimensional pigman tower, and I installed itemcollectors on Create’s safe library in the main world. However, when I approached the obsidian pigman tower in the nether, the game crashed and gave me this report.”

**Comment by SuperMartijn642** [comment]
Please fill in the template next time.

I fixed it now in Item Collectors version 1.1.9.
Thank you for reporting the issue!
