### ISSUE TITLE
[Crash] Crashed when I tried to interact with Item Collectors in 1.20.4 Fabric

### ISSUE THREAD

**Issue by kingkuys2123** [SuperMartijn642/ItemCollectors#32]
**Version Info**
 - Minecraft 1.20.4
 - Fabric 0.15.3
 - Fabric API 0.91.3
 - Java 20.0.2
 - ItemCollector 1.1.9

**Steps to Reproduce**
1. Place down an Item Collector
2. Open it by right-clicking
3. Crashed

**Crash report (~/logs/latest.log)**
https://pastebin.com/DsxsdVTK

**Comment by SuperMartijn642** [comment]
Fixed now in the dedicated versions for Minecraft 1.20.4.
Thank you for reporting the issue!
