### ISSUE TITLE
[Bug] Right-clicking collector doesn't cancel item interaction

### ISSUE THREAD

**Issue by IonNight** [SuperMartijn642/ItemCollectors#34]
**Version Info**
- Minecraft, 1.19.2
- Forge 43.3.8
- Item Collectors, 1.1.9

**Description of the Bug**
Held item gets destroyed or placed on the advanced item collector when you right click into the GUI. Same goes for the normal item collector as you can see in the video.

**Steps to Reproduce**
Hold an item like a chicken egg or a plank and right click on the advanced collector. 

**Screenshots**

https://github.com/SuperMartijn642/ItemCollectors/assets/27898087/3c510724-0c74-43a7-a2f7-257b49a60127

**Comment by SuperMartijn642** [comment]
Seems I already fixed when porting to Fabric and 1.20+ at some point.
I have now fixed it for Forge 1.12 to 1.19.4 in version 1.1.10.
Thank you for reporting the issue!
