### ISSUE TITLE
[Bug] 匹配 NBT 按钮可能导致无法连接至服务器/Matching NBT buttons may result in failure to connect to the server

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [SuperMartijn642/ItemCollectors#36]
# 基础信息/Basic Infomation
游戏版本: Minecraft 1.21
加载器类型: Fabric Loader
加载器版本:0.15.11
Fabric API 版本: 0.100.7
Mod 版本: 1.1.10

Game Version: Minecraft 1.21
ModLoader : Fabric Loader
Version: Fabric Loader 0.15.11
Fabric API Version:0.100.7
Mod Version:1.1.10

# 日志/Log:

[disconnect-2024-07-29_14.47.04-client.txt](https://github.com/user-attachments/files/16408896/disconnect-2024-07-29_14.47.04-client.txt)

# Bug 表现形式/Bug manifestations：

界面显示网络协议错误
日志出现空指针异常

The interface shows a network protocol error
Log appears `NullPointerException`

**Comment by kittykiller** [comment]
having the same issue on neoforge

[disconnect-2024-07-30_20.59.32-client.txt](https://github.com/user-attachments/files/16434606/disconnect-2024-07-30_20.59.32-client.txt)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.17a/b/d (depending on modloader) of my core library.
Thank you for reporting the issue!
