### ISSUE TITLE
[Bug] Minecraft Network Protocol Error 

### ISSUE THREAD

**Issue by danieltudor9** [SuperMartijn642/ItemCollectors#37]
**Version Info**
- Minecraft, 1.21
- Item Collectors,

**Description of the Bug**
During multiplayer other players lose connection when i whitelist items.

**Steps to Reproduce**
If i add items to the filter when i switch to whitelist thats the exact moment my friend gets the network error and D/C.

**Screenshots**
N/A, but i have the log if it helps.
[disconnect-2024-08-11_13.03.21-client.txt](https://github.com/user-attachments/files/16573363/disconnect-2024-08-11_13.03.21-client.txt)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.17a/b/d (depending on modloader) of my core library.
Thank you for reporting the issue!
