### ISSUE TITLE
More Filter Options

### ISSUE THREAD

**Issue by Shorepion** [SuperMartijn642/ItemCollectors#4]
**Is your feature request related to a problem? Please describe.**
Items collector does not pickup the same Items with different damage values (Bows in a skeleton farm)

**Describe the solution you'd like**
-Ignore Damage value of items filter

**Comment by SuperMartijn642** [comment]
Whoops I somehow missed the notification for this.
Anyways, that's a really good suggestion. I will see what I can do.

**Comment by SuperMartijn642** [comment]
I added a button to match durability for 1.12. In newer versions the durability is part of the item's nbt tag, so I added a button to match nbt.
It is added now in version 1.0.7.

Thanks for the suggestion!
