### ISSUE TITLE
[Bug] Item collector/Advanced item collector not picking up grown pure certus/fluix/nether quarts from Applied Energistics

### ISSUE THREAD

**Issue by StefanMalina** [SuperMartijn642/ItemCollectors#6]
**Version Info**
- Minecraft, 1.16.4
- mod version: 1.0.7 
- Forge version 35.1.15
- Item Collectors, advanced and regular

**Description of the Bug**
The Applied Energistics 2 items : Pure Certus/Fluix/Nether quartz are completely ignored by the collectors when grown from the quartz seeds of the respective items. and the seeds themselves are also completely ignored even when specifically whitelisted. (Yes i tried increasing the range with no effect. ( Although once a player picks up and throws the fully grown pure quartz near the vicinity of the collector it then picks them up just fine.(Except for the seeds themselves which are again, completely ignored.)))

**Steps to Reproduce**
Simply place either or both of the collectors on chests within range of a block of water containing the crystal seeds, 
And you can also throw the seeds themselves in random areas within the range of the collectors themselves. 
They simply won't be collected.

**Screenshots**
![2020-12-30_03 26 19](https://user-images.githubusercontent.com/76759991/103326100-20514180-4a4f-11eb-91fc-00af5bac3909.png)
![2020-12-30_03 26 21](https://user-images.githubusercontent.com/76759991/103326115-2b0bd680-4a4f-11eb-802f-6548a40f469e.png)

**Comment by StefanMalina** [comment]
in addition: item collectors also completely ignore charged certus quartz even when whitelisted.

**Comment by SuperMartijn642** [comment]
Whoops seems my notifications for this repository were disabled. I will have a look at why this happens.

**Comment by SuperMartijn642** [comment]
Seems Applied Energistics used their own ItemEntity instead of the vanilla one. I changed it now so any ItemEntity instance can be picked up in version 1.0.8.

Thanks for reporting the issue!
