### ISSUE TITLE
[Bug] Duping items with hopper and item collector

### ISSUE THREAD

**Issue by ZentZz** [SuperMartijn642/ItemCollectors#7]
**Version Info:**
- Minecraft 1.16
- Item Collectors 1.0.9

**Description of the Bug:**
Placing a chest, hopper and a item collector as the picture below and break a block on top of the hopper will dupe the item. Probably due to item collector collects item at the same tick as the hopper = two items.

**Steps to Reproduce:**
See picture below.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77157377/105363028-e3b2d900-5bfb-11eb-9189-d968a63943cf.png)

![image](https://user-images.githubusercontent.com/77157377/105363065-ee6d6e00-5bfb-11eb-95d7-b0c54599b71c.png)

![image](https://user-images.githubusercontent.com/77157377/105363094-f75e3f80-5bfb-11eb-821b-da94f69e0255.png)

**Comment by ZentZz** [comment]
Tested some more, dupes by dropping a item as well. See below setup:

![image](https://user-images.githubusercontent.com/77157377/105365134-34c3cc80-5bfe-11eb-86f1-4123ee4166a2.png)

![image](https://user-images.githubusercontent.com/77157377/105365156-3d1c0780-5bfe-11eb-929f-c2724e3cf81a.png)

**Comment by SuperMartijn642** [comment]
Apparently hoppers only set item entities to dead and don't remove the items from the item entities. I was only checking if the item entities still had items. I changed it so I ignore dead item entities.
It is fixed now in version 1.0.10.

Thanks for reporting the issue!
